Torsbranch
navikt/syfooversikt pull request #156
Opened 2020-09-30 08:07 UTC by torhrise

Ny tur for lps-planer

2020-09-30 08:08 UTC, cyanboy requested changes

2020-09-30 08:08 UTC, cyanboy commented on changelogs/4/tour.json
> +        },
Trailing komma, blir ikke gyldig json :)

2020-09-30 08:11 UTC, cyanboy approved these changes

2020-09-30 08:13 UTC, JMLindseth approved these changes

2021-04-29 11:45 UTC, janzh commented
PR is outdated and no longer relevant.

2021-04-29 11:45 UTC, closed without merging